name: Build and publish Docker image

on:
  push:
    branches: [ master ]
 
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Add Docker image metadata
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/vpowler/nginx-perl-file-upload-module
          tags: latest
          description: A Docker image for running Nginx with Perl file upload module

      - uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: true

