name: Build and publish Docker image

on:
  push:
    branches: [ master ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/vpowler/nginx-perl-file-upload-module:latest
          labels: |
            org.opencontainers.image.title=Nginx with Perl file upload module
            org.opencontainers.image.description=A Docker image for running Nginx with Perl file upload module
            org.opencontainers.image.source=https://github.com/vpowler/nginx-perl-file-upload-module

